### ISSUE TITLE
Frozen app using glymur

### ISSUE THREAD

**Issue by franfcunha** [quintusdias/glymur#431]
Hi,

I used a tool to freeze my Python application that uses glymur. Once I run it in another pc to test, glymur throws:

"You must have a version of OPENJPEG at least as high as 1.5.0 before you can read JPEG2000 images with glymur. Your version 1.3.0."

Of course in my root pc, from where I compiled the project glymur works perfectly! I also included the "linux dll" (.so) file openjp2 in my distribution folder. 
Does it means that the end-user must install openjpeg?
Please, any idea will be appreciate.

Cheers

**Comment by quintusdias** [comment]
It's probably failing because glymur cannot locate the openjp2 library and doesn't know where to look.  You might be able to get around this by having your application create a glymurrc configuration file that specifies where to find the openjp2 library when your application gets installed?  Check glymur.readthedocs.io for details.
